<?php 
    $Inmuebles=[
                    [
                        "Nombre del inmueble"=>"Residencial San Pablo",
                        "Direccion"=>"Heredia, Barva",
                        "Precio"=>"4000",
                        "imagen"=>["img/Casa1/Casa1.png", "img/Casa1/Baño1.jpg", "img/Casa1/1Cocina1.jpg", "img/Casa1/sala1.jpg", "img/Casa1/1cama1.jpg"],
                        "Tipo de casa"=>"En Residecial",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "3",
                        "Otros espacios"=> "garage, piscina",
                        "Codigo QR" => "img/Casa1/Codigo1.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Condominio Alfaro",
                        "Direccion"=>"Alajuela,San Ramon",
                        "Precio"=>"900",
                        "imagen"=>["img/Casa2/Casa2.jpeg","img/Casa2/Sala2.jpg", "img/Casa2/cn2.jpg","img/Casa2/2Cama.jpg","img/Casa2/2Baño2.jpg" ],
                        "Tipo de casa"=>"Casa en Alquiler",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Ático",
                        "Codigo QR" => "img/Casa2/QR2.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Casa en Vista de Mar",
                        "Direccion"=>" Guanacaste, Santa Cruz",
                        "Precio"=>"800",
                        "imagen"=>["img/Casa3/3Casa.jpg","img/Casa3/Sala3.jpg","img/Casa3/cn3.jpg","img/Casa3/Cuarto3.jpg","img/Casa3/Baño3.jpg" ],
                        "Tipo de casa"=>"Casa en Alquiler",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "1",
                        "Otros espacios"=> "piscina",
                        "Codigo QR" => "img/Casa3/QR3.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Condominio Labrador",
                        "Direccion"=>"Alajuela, San Mateo",
                        "Precio"=>"40000",
                        "imagen"=>["img/Casa4/Casa4.jpg", "img/Casa4/Sala4.jpg","img/Casa4/Cocina4.jpg","img/Casa4/4Cama.png","img/Casa4/Baño4.jpg" ],
                        "Tipo de casa"=>"Residencial",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "3",
                        "Otros espacios"=> "garage",
                        "Codigo QR" => "img/Casa4/QR4.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vecindario Cirri Sur",
                        "Direccion"=>"Alajuela, Naranjo",
                        "Precio"=>"1500",
                        "imagen"=>["img/Casa5/Casa5.jpg", "img/Casa5/Sala5.jpg","img/Casa5/Cocina5.jpg","img/Casa5/Cama5.jpg","img/Casa5/Baño5.jpg" ],
                        "Tipo de casa"=>"Casa en Alquiler",
                        "Numero de cuartos" =>"3",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "No cuenta con otros espacios",
                        "Codigo QR" => "img/Casa5/QR5.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Recidencial Rosa Linda",
                        "Direccion"=>"San Jose, Escazu ",
                        "Precio"=>"90000",
                        "imagen"=>["img/Casa6/Casa6.jpg","img/Casa6/Sala6.jpg","img/Casa6/Cocina6.jpg", "img/Casa6/Cuarto6.jpg","img/Casa6/Baño6.jpg"],
                        "Tipo de casa"=>"Casa en Residencial",
                        "Numero de cuartos" =>"3",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Piscina",
                        "Codigo QR" => "img/Casa6/QR6.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vecindario Aserri",
                        "Direccion"=>"San Jose, Aserri",
                        "Precio"=>"20000",
                        "imagen"=>["img/Casa7/Casa7.jpg", "img/Casa7/Sala7.jpg","img/Casa7/cn7.jpg", "img/Casa7/Cuarto7.jpg","img/Casa7/Baño7.jpg"],
                        "Tipo de casa"=>"Casa Fija",
                        "Numero de cuartos" =>"4",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Ático y Garage",
                        "Codigo QR" => "img/Casa7/QR7.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vecindario Guacimo",
                        "Direccion"=>"Limon, Guacimo",
                        "Precio"=>"800",
                        "imagen"=>["img/Casa8/Casa8.jpg", "img/Casa8/Sala8.jpg","img/Casa8/Cocina8.jpg", "img/Casa8/Cuarto8.jpg","img/Casa8/Baño8.jpg"],
                        "Tipo de casa"=>"Casa en Alquiler",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Garage",
                        "Codigo QR" => "img/Casa8/QR8.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Condominio San Rafael",
                        "Direccion"=>"San José, Desamparados",
                        "Precio"=>"1500",
                        "imagen"=>["img/Casa9/Casa9.jpg","img/Casa9/Sala9.jpg","img/Casa9/Cocina9.jpg","img/Casa9/cama9.jpg","img/Casa9/Baño9.jpg"],
                        "Tipo de casa"=>"Casa en Residencial",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "1",
                        "Otros espacios"=> "No contiene otros espacios",
                        "Codigo QR" => "img/Casa9/QR9.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vecendario Barrantes",
                        "Direccion"=>"Heredia, Flores",
                        "Precio"=>"1050",
                        "imagen"=>["img/Casa10/Casa10.jpg","img/Casa10/Sala.jpg","img/Casa10/cn10.jpg","img/Casa10/Cuarto10.jpg","img/Casa10/Baño10.png" ],
                        "Tipo de casa"=>"Casa en Alquiler",
                        "Numero de cuartos" =>"3",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Garage y piscina",
                        "Codigo QR" => "img/Casa10/QR10.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vecindario San Vicente",
                        "Direccion"=>"San jose, Moravia",
                        "Precio"=>"1500",
                        "imagen"=>["img/Casa11/Casa11.jpg","img/Casa11/Sala11.png","img/Casa11/Cocina11.jpg","img/Casa11/Cuarto11.png","img/Casa11/11Baño.jpg"],
                        "Tipo de casa"=>"Casa",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Ático",
                        "Codigo QR" => "img/Casa11/QR11.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Apartamentos Catalina",
                        "Direccion"=>"San Jose, Escazu" ,
                        "Precio"=>"450",
                        "imagen"=>["img/Casa12/Residencial.jpg","img/Casa12/Sala12.jpg","img/Casa12/Cocina12.jpg","img/Casa12/Cuarto12.jpg","img/Casa12/Baño12.jpg"],
                        "Tipo de casa"=>"Apartamento en Alquiler",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "1",
                        "Otros espacios"=> "Garage",
                        "Codigo QR" => "img/Casa12/QR12.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Residencial Tejar",
                        "Direccion"=>"Cartago, Turrialba",
                        "Precio"=>"8000",
                        "imagen"=>["img/Casa13/Casa13.jpg","img/Casa13/Sala13.jpg","img/Casa13/Cocina13.jpg","img/Casa13/Cuarto13.jpg","img/Casa13/Baño13.jpg"],
                        "Tipo de casa"=>"Casa",
                        "Numero de cuartos" =>"4",
                        "Numero de baños" => "3",
                        "Otros espacios"=> "Piscina",
                        "Codigo QR" => "img/Casa13/QR13.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vecindario San Tomas",
                        "Direccion"=>"Heredia, Santo Domingo",
                        "Precio"=>"5050",
                        "imagen"=>["img/Casa14/Casa14.jpg","img/Casa14/Sala14.jpg","img/Casa14/Cocina14.jpg","img/Casa14/Cuarto14.jpg","img/Casa14/Baño14.jpg"],
                        "Tipo de casa"=>"Casa",
                        "Numero de cuartos" =>"3",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Garage y Piscina",
                        "Codigo QR" => "img/Casa14/QR14.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vecindario Perez",
                        "Direccion"=>"San Jose, Perez Zeledon",
                        "Precio"=>"7000",
                        "imagen"=>["img/Casa15/Casa15.jpg","img/Casa15/Sala15.jpg","img/Casa15/Cocina15.jpg","img/Casa15/Cuarto15.jpg","img/Casa15/Baño15.jpg"],
                        "Tipo de casa"=>"Casa fija",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "1",
                        "Otros espacios"=> "No contiene otros espacios",
                        "Codigo QR" => "img/Casa15/QR15.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vecindario San Miguel",
                        "Direccion"=>"Heredia, Santo Domingo",
                        "Precio"=>"650",
                        "imagen"=>["img/Casa16/Casa16.jpg","img/Casa16/Sala16.jpg","img/Casa16/Cocina16.jpg","img/Casa16/Cuarto16.jpg","img/Casa16/Baño16.jpg"],
                        "Tipo de casa"=>"Apartamento en Alquiler",
                        "Numero de cuartos" =>"1",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Garage y Terraza",
                        "Codigo QR" => "img/Casa16/QR16.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vecindario La Garita",
                        "Direccion"=>"Guanacaste, la cruz",
                        "Precio"=>"500",
                        "imagen"=>["img/Casa17/Casa17.jpg","img/Casa17/Sala17.jpg","img/Casa17/Cocina17.jpg","img/Casa17/Cama17.jpg","img/Casa17/Baño17.jpg"],
                        "Tipo de casa"=>"Casa Fija",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Garage y Terraza",
                        "Codigo QR" => "img/Casa17/QR17.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vista de mar",
                        "Direccion"=> "Puntarenas, Golfito",
                        "Precio"=>"8500",
                        "imagen"=>["img/Casa18/Casa18.jpg","img/Casa18/Sala18.jpg","img/Casa18/Cocina18.jpg","img/Casa18/Cama18.jpg","img/Casa18/Bañi18.jpg"],
                        "Tipo de casa"=>"Casa Fija",
                        "Numero de cuartos" =>"3",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Garage y Terraza",
                        "Codigo QR" => "img/Casa18/QR18.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Condominio Guapiles",
                        "Direccion"=>"Limon, Pococi",
                        "Precio"=>"3000",
                        "imagen"=>["img/Casa19/Casa19.jpg","img/Casa19/Sala19.png","img/Casa19/Cocina19.jpg","img/Casa19/Cama19.jpg","img/Casa19/Baño19.jpg"],
                        "Tipo de casa"=>"Casa Fija",
                        "Numero de cuartos" =>"3",
                        "Numero de baños" => "2",
                        "Otros espacios"=> "Garage",
                        "Codigo QR" => "img/Casa19/QR19.png",
                    ],
                    [
                        "Nombre del inmueble"=>"Vista de Mar",
                        "Direccion"=>"Puntarenas, Quepos",
                        "Precio"=>"12000",
                        "imagen"=>["img/Casa20/Casa20.jpg","img/Casa20/Sala20.jpg","img/Casa20/Cocina20.jpg","img/Casa20/Cama20.jpg","img/Casa20/Baño20.jpg"],
                        "Tipo de casa"=>"Casa en Alquiler",
                        "Numero de cuartos" =>"2",
                        "Numero de baños" => "1",
                        "Otros espacios"=> "Garage",
                        "Codigo QR" => "img/Casa20/QR20.png",
                    ],

                    ]               
?>